### ISSUE TITLE
节点数据修改时，整列的滚动动画发生重绘

### ISSUE THREAD

**Issue by 4tj** [tinglejs/tingle-slot#4]

**Comment by gbk** [comment]
这块有点纠结啊

看了你的代码，你的数据确实是发生变化了，比方说 第二列选中的 14 点 本来索引在第一个的，数据变化之后变成了第 14 个，选中索引的变动会触发滚动动画

但如果你说值相同，即便选中索引变化，也不触发动画，那么又有问题了，一列中是允许有重复值的，碰到这种重复值怎么办？

如果要细粒度到每次赋值、每一列选中索引的改变是否触发动画，那么这个赋值就得重新设计了。。唉～

**Comment by gbk** [comment]
v0.2.3

**Comment by 4tj** [comment]
非常完美！
